### ISSUE TITLE
bankai throws when used with firefox

### ISSUE THREAD

**Issue by toddself** [choojs/bankai#217]
Firefox is requesting favicon.ico always.  We need to handle this correctly.

```
/home/todd/src/bankai/node_modules/wayfarer/index.js:63
    throw new Error("route '" + route + "' did not match")
    ^

Error: route '/favicon.ico' did not match
    at emit (/home/todd/src/bankai/node_modules/wayfarer/index.js:63:11)
    at Choo.emit [as router] (/home/todd/src/bankai/node_modules/nanorouter/index.js:46:24)
    at Choo.toString (/home/todd/src/bankai/node_modules/choo/index.js:186:19)
    at detectRouter (/home/todd/src/bankai/lib/detect-router.js:5:16)
    at EventEmitter.Bankai.html (/home/todd/src/bankai/index.js:166:14)
    at Server.handler (/home/todd/src/bankai/bin/start.js:121:16)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by toddself** [comment]
This is oddly getting caught by the `else if` clause on line 90 where the url is `/` or the headers have `accept html` in them...
