### ISSUE TITLE
error when accessing static file

### ISSUE THREAD

**Issue by justinj** [choojs/bankai#224]
I have a project created by `choo-cli`, my package.json is as follows:

```
{
  "name": "leved",
  "version": "1.0.0",
  "description": "Created with choo-cli",
  "main": "client.js",
  "scripts": {
    "start": "bankai client.js -p 8080 --open",
    "build:prod": "bankai build client.js dist/",
    "lint": "standard --verbose | snazzy",
    "test": "npm run lint"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "choo": "^4.1.0"
  },
  "devDependencies": {
    "bankai": "^5.3.0",
    "snazzy": "^6.0.0",
    "standard": "^8.6.0"
  }
}
```

If I run `npm start` and then hit `assets/file.png` (which exists in my `assets`) directory, bankai crashes with this error:

```
/Users/justin/repos/leved/node_modules/send/index.js:303
  res.setHeader('Content-Type', 'text/html; charset=UTF-8')
      ^

TypeError: res.setHeader is not a function
    at SendStream.error (/Users/justin/repos/leved/node_modules/send/index.js:303:7)
    at SendStream.onStatError (/Users/justin/repos/leved/node_modules/send/index.js:435:12)
    at onstat (/Users/justin/repos/leved/node_modules/send/index.js:740:26)
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by justinj** [comment]
I see, ok! Thanks for the tip!
