### ISSUE TITLE
`mkdirp not found`

### ISSUE THREAD

**Issue by toddself** [choojs/bankai#236]
`mkdirp` is a devDependency, but required by `lib/cmd-build.js`, and `lib/http-server.js`

```
$ git clone git@github.com:choojs/bankai
$ cd bankai
$ git checkout new-new-new
$ npm i -g .
$ bankai --version
module.js:491
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/todd/.nvm/versions/node/v8.4.0/lib/node_modules/bankai/lib/cmd-build.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by yoshuawuyts** [comment]
Fixed! Thanks for reporting :D
