### ISSUE TITLE
`bankai build` throws exception when there's `async/await` in the code

### ISSUE THREAD

**Issue by poga** [choojs/bankai#239]
bankai version: `v9.0.0-1`

Hi, just started using choo and bankai.

I have a choo app working fine with `bankai start -V app/index.js`, but throws following exception when I tried to build the app with `bankai build app/index.js`:

```
SyntaxError: Unexpected token (82:10)
    at Parser.pp$4.raise (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.semicolon (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:600:59)
    at Parser.pp$1.parseExpressionStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1025:8)
    at Parser.pp$1.parseStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:780:22)
    at Parser.pp$1.parseBlock (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2362:22)
    at Parser.pp$1.parseFunction (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1132:8)
    at Parser.pp$1.parseFunctionStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:868:15)
    at Parser.pp$1.parseStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:739:17)
```

The app code is at [https://github.com/poga/civic-notebook/blob/0f722524e04643310b74901156fb0f26479e61cc/app/index.js#L82](https://github.com/poga/civic-notebook/blob/0f722524e04643310b74901156fb0f26479e61cc/app/index.js#L82)

If I remove `async` and `await`. bankai builds successfully.

How do I enable async and await for bankai's building process?

**Comment by timwis** [comment]
Shoot I thought I whacked the last mole for this... Does the build script do any kind of static analysis that bankai start doesn't? (Or, literally, use a module that uses an old version of acorn)

**Comment by poga** [comment]
I think it's `unassertify`:

```
[~/projects/civic-notebook] (master) 0h0m 🐱  npm i unassertify
npm WARN civic-notebook@1.0.0 No description
npm WARN civic-notebook@1.0.0 No repository field.

+ unassertify@2.0.4
updated 1 package in 9.959s


[~/projects/civic-notebook] (master) 13h49m 🐱  ./node_modules/.bin/browserify -t unassertify app/index.js
/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2490
  throw err
  ^

SyntaxError: Unexpected token (82:10)
    at Parser.pp$4.raise (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.semicolon (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:600:59)
    at Parser.pp$1.parseExpressionStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1025:8)
    at Parser.pp$1.parseStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:780:22)
    at Parser.pp$1.parseBlock (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:2362:22)
    at Parser.pp$1.parseFunction (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:1132:8)
    at Parser.pp$1.parseFunctionStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:868:15)
    at Parser.pp$1.parseStatement (/Users/poga/projects/civic-notebook/node_modules/unassertify/node_modules/acorn/dist/acorn.js:739:17)
```

**Comment by timwis** [comment]
That looks like the culprit! Would you mind trying the following?

1. Clone the `unassertify` repo and the `bankai` repo locally
2. Inside the `unassertify` directory, run `npm link`
3. Inside the `bankai` repo, run `npm link unassertify`
4. Reproduce your issue, perhaps by modifying the `example` directory and running `node bin/build.js`
5. Inside the `unassertify` directory, run `npm install acorn@latest`
6. Try reproducing your issue again. If it's fixed, weeee! If not, it looks like `unassertify` also uses the `unassert` module, so we may need to upgrade it there too.
7. Assuming this fixes your issue, run `npm test` inside the `unassertify` directory to verify there aren't regressions, then submit a pull request to `unassertify` (should be just the version change in `package.json`)

That's what I did for [these repos](https://github.com/browserify/browserify/issues/1667).

**Comment by poga** [comment]
I tried the steps. Unfortunately, the issue persists.

Here's what I've done:

1. Clone `unassertify`, `bankai`, and `unassert`. `npm i` in all 3 repos.
2. `npm i acorn@latest` and `npm link` in both `unassertify` and `unassert` repo.
3. `npm link unassertify` and `npm link unassert` in `bankai` repo.
4. test with my app, still throw the same exception.

I've noticed that `espurify` (used by `unassert`) also pinned on acorn v4. Yet, updating it still not fixing the issue.

On a side note, `npm test` failed in `unassertify` even with a fresh clone.

**Comment by poga** [comment]
btw here's the full stacktrace:

```
[~/projects/bankai] (master) 352h46m 🐱  node --stack-trace-limit=1000 bin/index.js build example/test.js dist/
23:11:21 ✨  bankai example/assets/icon.png done
/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:2490
  throw err
  ^

SyntaxError: Unexpected token (80:10)
    at Parser.pp$4.raise (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.semicolon (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:600:59)
    at Parser.pp$1.parseExpressionStatement (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:1025:8)
    at Parser.pp$1.parseStatement (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:780:22)
    at Parser.pp$1.parseBlock (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:2362:22)
    at Parser.pp$1.parseFunction (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:1132:8)
    at Parser.pp$1.parseFunctionStatement (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:868:15)
    at Parser.pp$1.parseStatement (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:739:17)
    at Parser.pp$1.parseBlock (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$3.parseFunctionBody (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:2362:22)
    at Parser.pp$1.parseFunction (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:1132:8)
    at Parser.pp$1.parseFunctionStatement (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:868:15)
    at Parser.pp$1.parseStatement (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:739:17)
    at Parser.pp$1.parseTopLevel (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:672:23)
    at Parser.parse (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:529:15)
    at Object.parse (/Users/poga/projects/unassertify/node_modules/acorn/dist/acorn.js:3378:37)
    at applyUnassertWithoutSourceMap (/Users/poga/projects/unassertify/index.js:73:21)
    at Stream.end (/Users/poga/projects/unassertify/index.js:97:26)
    at _end (/Users/poga/projects/unassertify/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/poga/projects/unassertify/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/poga/projects/bankai/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at endReadableNT (/Users/poga/projects/bankai/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

`unassertify` is definitely the culprit. I'm not sure why above fixes don't work...

**Comment by yoshuawuyts** [comment]
Odd :/ Not sure what's up, but could you maybs check the new-new-new branch
and see if you can repro?

**Comment by poga** [comment]
I tried to build with `new-new-new` branch and here's the output: https://gist.github.com/poga/ed0a07c5a1b4d8a90c55db3f0c3792ad

Looks like the app builds successfully.

But when I tried to start development server with `new-new-new` branch, the server just quit and clear the screen so I can't see if there's any output.

**Comment by yoshuawuyts** [comment]
Oh no! Try the -q flag for the last one. We should make errors better for
sure (working on that today)

**Comment by poga** [comment]
Thanks for the quick reply. From what I've seen with the `-q` flag, `bankai` is trying to prerender my choo app. 

Since my app will connect a backend API (which I didn't boot up), prerender failed and `bankai` throw the exception. It works when the backend API is accessible.

Thanks for the great work on choo and bankai! I'm closing this.
