### ISSUE TITLE
Error in error printing code

### ISSUE THREAD

**Issue by s3ththompson** [choojs/bankai#247]
In trying to print this error...
```
{ Error: Cannot find module './static/css/base.css' from '/Users/seththompson/code/oy-spheres/app' while parsing file: /Users/seththompson/code/oy-spheres/app/index.js
    at Function.module.exports [as sync] (/Users/seththompson/code/oy-spheres/node_modules/resolve/lib/sync.js:33:11)
    at resolveSync (/Users/seththompson/code/oy-spheres/node_modules/style-resolve/index.js:22:19)
    at extractImportNodes (/Users/seththompson/code/oy-spheres/node_modules/sheetify/transform.js:112:27)
    at extractNodes (/Users/seththompson/code/oy-spheres/node_modules/sheetify/transform.js:85:7)
    at walk (/Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:49:9)
    at /Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:46:17
    at forEach (/Users/seththompson/code/oy-spheres/node_modules/foreach/index.js:12:16)
    at walk (/Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:34:9)
    at /Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:41:25
    at forEach (/Users/seththompson/code/oy-spheres/node_modules/foreach/index.js:12:16)
    at /Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:39:17
    at forEach (/Users/seththompson/code/oy-spheres/node_modules/foreach/index.js:12:16)
    at walk (/Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:34:9)
    at module.exports (/Users/seththompson/code/oy-spheres/node_modules/falafel/index.js:50:7)
    at DestroyableTransform.end [as _flush] (/Users/seththompson/code/oy-spheres/node_modules/sheetify/transform.js:59:13)
    at DestroyableTransform.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at prefinish (/Users/seththompson/code/oy-spheres/node_modules/readable-stream/lib/_stream_writable.js:596:14)
    at finishMaybe (/Users/seththompson/code/oy-spheres/node_modules/readable-stream/lib/_stream_writable.js:604:5)
    at endWritable (/Users/seththompson/code/oy-spheres/node_modules/readable-stream/lib/_stream_writable.js:615:3)
  filename: '/Users/seththompson/code/oy-spheres/app/index.js' }
```
Bankai throws in `lib/tty-error.js`:

```
/Users/seththompson/code/oy-spheres/node_modules/bankai/lib/tty-error.js:15
  var line = loc.line
                ^

TypeError: Cannot read property 'line' of undefined
    at ttyError (/Users/seththompson/code/oy-spheres/node_modules/bankai/lib/tty-error.js:15:17)
    at Readable.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/bankai/lib/graph-script.js:64:15)
    at emitOne (events.js:120:20)
    at Readable.emit (events.js:210:7)
    at Labeled.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:115:13)
    at Labeled.emit (events.js:210:7)
    at Labeled.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:115:13)
    at Labeled.emit (events.js:210:7)
    at Deps.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:115:13)
    at Deps.emit (events.js:210:7)
    at DuplexWrapper.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/module-deps/index.js:250:18)
    at emitOne (events.js:115:13)
    at DuplexWrapper.emit (events.js:210:7)
    at DestroyableTransform.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/stream-combiner2/node_modules/duplexer2/index.js:45:12)
    at emitOne (events.js:115:13)
    at DestroyableTransform.emit (events.js:210:7)
    at DestroyableTransform.end [as _flush] (/Users/seththompson/code/oy-spheres/node_modules/sheetify/transform.js:61:19)
    at DestroyableTransform.<anonymous> (/Users/seththompson/code/oy-spheres/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:314:30)
```

**Comment by yoshuawuyts** [comment]
Ahhh, yeah good point - we should def fix this. Whoops 😓
