### ISSUE TITLE
unhandled 'error' 

### ISSUE THREAD

**Issue by verpixelt** [choojs/bankai#257]
I've clone the latest version of Bankai just a few min ago. That's the error I ran into:
(node 8.0.0 npm 5.0.0)
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected character '#' (1:0) while parsing file: /Users/verpixelt/projects/bankai/node_modules/JSONStream/index.js
    at Parser.pp$4.raise (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:2610:13)
    at Parser.pp$8.getTokenFromCode (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:3252:8)
    at Parser.pp$8.readToken (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:2975:15)
    at Parser.pp$8.nextToken (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:2966:15)
    at Parser.parse (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:542:8)
    at parse (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/node_modules/acorn/dist/acorn.js:3669:37)
    at module.exports (/usr/local/lib/node_modules/bankai/node_modules/falafel/index.js:22:15)
    at DestroyableTransform.end [as _flush] (/usr/local/lib/node_modules/bankai/node_modules/yo-yoify/index.js:56:13)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/bankai/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:312:19)
```

![image](https://user-images.githubusercontent.com/1640079/31090108-c817ee86-a7a6-11e7-8b2d-5029bbda2187.png)

**Comment by yoshuawuyts** [comment]
Ohey; that's unfortunate, looks like it was a prior version - try running
the bankai beta: `npm i bankai@next`! :D
