### ISSUE TITLE
unable to work with sass

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#377]
This is my package.json, I have included the `sheetify-sass` plugin:
```
"browserify": {
    "transform": [
      [
        "sheetify",
        {
          "transform": [
            [
              "sheetify-sass"
            ]
          ]
        }
      ]
    ]
  }
```

After `bankai start index.js`, it throws:

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:199:11)
    at BufferGraph.node (/Users/zhouhancheng/编程/myblog/node_modules/bankai/lib/graph-style.js:31:31)
    at /Users/zhouhancheng/编程/myblog/node_modules/buffer-graph/index.js:101:17
    at Array.forEach (<anonymous>)
    at /Users/zhouhancheng/编程/myblog/node_modules/buffer-graph/index.js:96:22
    at /Users/zhouhancheng/编程/myblog/node_modules/bankai/lib/graph-script.js:116:9
    at /Users/zhouhancheng/编程/myblog/node_modules/bankai/lib/exorcise.js:59:5
    at /Users/zhouhancheng/编程/myblog/node_modules/bankai/lib/exorcise.js:25:5
    at ConcatStream.<anonymous> (/Users/zhouhancheng/编程/myblog/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:164:20)
```

When I use `budo index.js --live` or change the sass syntax to css, there's no such error.

node 9.2.0
npm 5.6.0

**Comment by ZhouHansen** [comment]
I will post a more detailed issue later.
