### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined at Object.exports.removeComments

### ISSUE THREAD

**Issue by srilq** [choojs/bankai#418]
```
> NODE_ENV=production bankai build

14:56:54 ✨  Compiling & compressing files

14:56:54 ✨  created: dist
14:56:54 ✨  created: dist/manifest.json
14:56:54 ✨  created: dist/manifest.json.gz
14:56:54 ✨  created: dist/manifest.json.deflate
14:56:54 ✨  created: dist/manifest.json.br
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'replace' of undefined
    at Object.exports.removeComments (/Users/sril/src/stef/node_modules/combine-source-map/index.js:151:12)
    at DestroyableTransform.write [as _transform] (/Users/sril/src/stef/node_modules/browser-pack/index.js:74:30)
    at DestroyableTransform.Transform._read (/Users/sril/src/stef/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/sril/src/stef/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/sril/src/stef/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/sril/src/stef/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/sril/src/stef/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at DestroyableTransform.ondata (/Users/sril/src/stef/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
```

Relevant links:
* [`combine-source-map/index.js:153`](https://github.com/thlorenz/combine-source-map/blob/master/index.js#L153)
* [`browser-pacek/index.js:75`](https://github.com/browserify/browser-pack/blob/master/index.js#L75)

Deps:
```
"devDependencies": {
  "bankai": "^9.5.1"
},
"dependencies": {
  "bel": "^5.1.6",
  "choo": "^6.7.0",
  "choo-devtools": "^2.3.3",
  "choo-log": "^8.0.0",
  "normalize.css": "^8.0.0",
  "sheetify": "^7.2.0"
}
```

**Comment by goto-bus-stop** [comment]
Dang that's really strange! Somehow browserify ends up with a file that has no contents at all 😕 

if this only happens for some apps and not others, can you share a reproduction that causes it to fail like this?
otherwise seeing the contents of `row` in browser-pack just before it fails could be really useful too; adding a line like this in node_modules/browser-pack/index.js just before the `var wrappedSource` line should do it:

```js
if (!row.source) console.log(row)
```

**Comment by srilq** [comment]
@goto-bus-stop I'm afraid this is only occurring with this app, and only when running `bankai build` (`bankai start` works fine) and also only in `NODE_ENV=development` (as would be expected as this is related to source maps).

I've pushed my branch:
[[srilq/bankai-bug]](https://github.com/srilq/stef/tree/srilq/bankai-bug)

As you can see, the build succeeds in production env:
Build log: https://app.netlify.com/sites/stef/deploys/5a835a777b6ee8691525bc33
Live site: https://5a835a777b6ee8691525bc33--stef.netlify.com/

**Comment by srilq** [comment]
Wait a sec... no sorry, it's occurring locally when running `NODE_ENV=production bankai build` but it succeeds in the Netlify build, so it's not related to the env var but rather the environment itself, which is curious...

**Comment by goto-bus-stop** [comment]
yeah, seeing this too! this is because of an old bug in browser-pack-flat that was fixed in https://github.com/goto-bus-stop/browser-pack-flat/commit/ee119540133e6d1f12b999a6bbcb50daa37e303a (released as 3.0.1), but the package-lock.json in your repo still has it pinned to 3.0.0. running `npm update` should fix it locally, could you check if that helps?

it's a bit unfortunate that npm@5 doesn't update existing deps on `npm install` anymore; makes this sort of thing easier to run into…

**Comment by srilq** [comment]
I just tried deleting `package-lock.json` and `node_modules` and running `npm i` and `bankai build` seems to be working now, but now `bankai start` is having issues! 🙈 I'll try to work out what on earth is going on now. Thanks for the help!

**Comment by srilq** [comment]
@goto-bus-stop Would you be able to try `npm start` or `npx -c "bankai start"` on the latest commit on the above branch. 😕

I'm getting this:
```
> NODE_ENV=development bankai start

A critical error occured, forcing Bankai to abort:

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1246:7)
    at iterator (/Users/sril/src/stef/node_modules/findup/index.js:31:28)
    at FindUp._find (/Users/sril/src/stef/node_modules/findup/index.js:60:3)
    at new FindUp (/Users/sril/src/stef/node_modules/findup/index.js:53:8)
    at FindUp (/Users/sril/src/stef/node_modules/findup/index.js:15:12)
    at module.exports (/Users/sril/src/stef/node_modules/findup/index.js:10:10)
    at isElectronProject (/Users/sril/src/stef/node_modules/bankai/lib/is-electron-project.js:9:3)
    at start (/Users/sril/src/stef/node_modules/bankai/lib/cmd-start.js:12:3)
    at main (/Users/sril/src/stef/node_modules/bankai/bin.js:90:31)
```
Note that this doesn't crash when running `npx bankai start` (without the `-c`), but it seems to get stuck on `starting`.

![screen shot 2018-02-13 at 11 17 01 pm](https://user-images.githubusercontent.com/18026180/36179398-0ae6850c-1114-11e8-9285-7d62bf494e70.png)
