### ISSUE TITLE
A critical error occured, forcing Bankai to abort

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#434]
# Update to 9.7.1 creates critical error

Run:
```bankai start index.js```

Produces:
```
A critical error occured, forcing Bankai to abort:

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at /Users/.../node_modules/browserify-persist-fs/index.js:204:39
    at /Users/.../node_modules/module-deps/index.js:422:25
    at ConcatStream.<anonymous> (/Users/.../node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:165:20)
    at finishMaybe (/Users/.../node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/Users/.../node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/Users/.../node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/Users/.../node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:255:19)
```

**Comment by shotlom** [comment]
v.9.4
Works

**Comment by goto-bus-stop** [comment]
:package: 9.7.2
