### ISSUE TITLE
Can't require Bankai/http

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/bankai#470]
This a 🐛 bug report

## Expected Behavior

This should work (as the readme say)
```js
var bankaiHttp = require('bankai/http')
```

## Current Behavior

```
Error: Cannot find module 'bankai/http'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/yerko/.nvm/versions/node/v9.7.1/lib/node_modules/mtalk/bin.js:11:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)

```
## Possible Solution

Add a `files` section to package.json.

I think that adding index.js and bin.js would be enough

**Comment by goto-bus-stop** [comment]
Wuuh. It's in the package though! https://unpkg.com/bankai@9.11.1/

**Comment by YerkoPalma** [comment]
Last time I checked was still an issue. Let me explain my context.
I have a package here (https://github.com/YerkoPalma/mtalk) where I have bankai as a dependency and where I require bankai/http, and it works fine. But when I install that package (`npm i -g mtalk`) I get the error posted. Migth be my error, just don't know why (I guess that if you install the package you'll see the same error)

**Comment by goto-bus-stop** [comment]
hmm no that works fine for me :confounded:
