### ISSUE TITLE
Test #163 failing (on Ubuntu 18.10, Node v10.14.2)

### ISSUE THREAD

**Issue by aral** [choojs/bankai#520]
This is this a 🐛 bug report.

## Expected Behavior

All tests should pass.

## Current Behavior

Test 163 fails.

```sh
not ok 163 should be truthy
  ---
    operator: ok
    expected: true
    actual:   false
    at: <anonymous> (/home/aral/ind.ie/hypha/spikes/bankai/test/build.js:86:12)
    stack: |-
      Error: should be truthy
          at Test.assert [as _assert] (/home/aral/ind.ie/hypha/spikes/bankai/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/aral/ind.ie/hypha/spikes/bankai/node_modules/tape/lib/test.js:77:32)
          at Test.assert (/home/aral/ind.ie/hypha/spikes/bankai/node_modules/tape/lib/test.js:344:10)
          at Test.bound [as ok] (/home/aral/ind.ie/hypha/spikes/bankai/node_modules/tape/lib/test.js:77:32)
          at /home/aral/ind.ie/hypha/spikes/bankai/test/build.js:86:12
          at ChildProcess.<anonymous> (/home/aral/ind.ie/hypha/spikes/bankai/test/build.js:16:21)
          at ChildProcess.emit (events.js:182:13)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
  ...
```

## Your Environment

* Node.js v10.14.2
* Ubuntu 18.10
* Master branch

**Comment by goto-bus-stop** [comment]
probably just need to update the hash … it might change with dependency updates i suppose :(

**Comment by goto-bus-stop** [comment]
Thanks for the report! :+1:

**Comment by aral** [comment]
Thanks for the fix :) 👍
